// flow-typed signature: 230b4cc8a3937090856055336d181e7d
// flow-typed version: <<STUB>>/express-no-favicons_v^0.0.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'express-no-favicons'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'express-no-favicons' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */


// Filename aliases
declare module 'express-no-favicons/index' {
  declare module.exports: $Exports<'express-no-favicons'>;
}
declare module 'express-no-favicons/index.js' {
  declare module.exports: $Exports<'express-no-favicons'>;
}
