// flow-typed signature: 61c3dd98639448de4fa95592b698cbaa
// flow-typed version: <<STUB>>/react-async-bootstrapper_v^1.1.1/flow_v0.54.0

/**
 * This is an autogenerated libdef stub for:
 *
 *   'react-async-bootstrapper'
 *
 * Fill this stub out by replacing all the `any` types.
 *
 * Once filled out, we encourage you to share your work with the
 * community by sending a pull request to:
 * https://github.com/flowtype/flow-typed
 */

declare module 'react-async-bootstrapper' {
  declare module.exports: any;
}

/**
 * We include stubs for each file inside this npm package in case you need to
 * require those files directly. Feel free to delete any files that aren't
 * needed.
 */
declare module 'react-async-bootstrapper/commonjs/index' {
  declare module.exports: any;
}

declare module 'react-async-bootstrapper/umd/react-async-bootstrapper' {
  declare module.exports: any;
}

declare module 'react-async-bootstrapper/umd/react-async-bootstrapper.min' {
  declare module.exports: any;
}

// Filename aliases
declare module 'react-async-bootstrapper/commonjs/index.js' {
  declare module.exports: $Exports<'react-async-bootstrapper/commonjs/index'>;
}
declare module 'react-async-bootstrapper/umd/react-async-bootstrapper.js' {
  declare module.exports: $Exports<'react-async-bootstrapper/umd/react-async-bootstrapper'>;
}
declare module 'react-async-bootstrapper/umd/react-async-bootstrapper.min.js' {
  declare module.exports: $Exports<'react-async-bootstrapper/umd/react-async-bootstrapper.min'>;
}
